import React from 'react'
import { List, Avatar } from 'antd'

const Movies = (props) => {
  return (
    <List
      itemLayout="horizontal"
      dataSource={props.data}
      renderItem={item => (
        <List.Item>
          <List.Item.Meta
            avatar={<Avatar src="https://icons-for-free.com/iconfiles/png/512/movie+video+icon-1320087274946223173.png" />}
            title={<a href={`https://www.imdb.com/find?q=${item.title}`}>{item.title}</a>}
            description={item.content}
          />
          <div>Generated by {item.author}</div>
        </List.Item>
      )}
    />
  )
}

export default Movies